#环境语言
language: java
#所选服务
services:
  - docker
#权限
sudo: required
#分支
branches:
  only:
    - master
#执行脚本
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build . -t "soldierdocker/atm:latest"
#安装之前执行脚本
before_install:
  - openssl aes-256-cbc -K $encrypted_a7dfe7f624ec_key -iv $encrypted_a7dfe7f624ec_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#成功之后执行的脚本
after_success:
  - docker login -u=$DOCKER_NAME -p="$DOCKER_PWD"
  - docker push soldierdocker/atm:latest
  - chmod 600 ~/.ssh/id_rsa
  - rsync -az --delete ./docker-compose.yml root@$IP:/usr/local/project_backup/ATM/
  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$IP "cd /usr/local/project_backup/ATM/;sudo docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml up -d;exit"